config/routes.rb
TwitterClone::Application.routes.draw do

  get "followerships/create"

  get "followerships/destroy"

  get "posts/create"

  get "posts/destroy"

  get "main/home"

  get "main/help"

  get "main/about"

  root :to => "main#home"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :users
  resources :sessions
  resources :posts
  resources :followerships

end

app/models/followership.rb
class Followership < ActiveRecord::Base
  attr_accessible :followed_id

  # Conencts two of the same class type.
  # We have to assign names and type explicitly
  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"


  # TODO: Validates both IDs!!!
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content

  belongs_to :user

  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

  default_scope :order => 'posts.created_at DESC'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :name, :email, :password, :password_confirmation

  validates_uniqueness_of :email

  has_many :posts, :dependent => :destroy

  #TODO: Add destruction dependences in all these!

  has_many :followerships, :foreign_key => "follower_id"

  has_many :reverse_followerships, :foreign_key => "followed_id", :class_name => "Followership"

  has_many :following, :through => :followerships, :source => :followed

  has_many :followers, :through => :reverse_followerships,
                       :source  => :follower

  def following?(to_follow)
    followerships.find_by_followed_id(to_follow)
  end

  def follow(to_follow)
    followerships.create(:followed_id => to_follow.id)
  end

  def unfollow(to_not_follow)
    # Double check that we're actually following before doing anything
    if following?(to_not_follow)
      followerships.find_by_followed_id(to_not_follow).destroy
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] && User.exists?(session[:user_id])
  end

  def is_user_authenticated?
    !current_user.nil?
  end

  def authenticate_user!
    if !is_user_authenticated?
      redirect_to login_url 
    end
  end

  helper_method :current_user
  helper_method :is_user_authenticated?
  helper_method :authenticate_user!
end

app/controllers/followerships_controller.rb
class FollowershipsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @user = User.find(params[:followership][:followed_id])
    current_user.follow(@user)
    redirect_to @user
  end

  def destroy
    @user = Followership.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_to @user
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    if is_user_authenticated?
      # TODO: Is there better way to do this?
      @post = Post.new
      #TODO: Should be an aggegate feed, not just my own posts
      @posts = current_user.posts.all
    end
  end

  def help
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      redirect_to root_path
    else
      render 'main/home'
    end
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where("email = ?", params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url 
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
    
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      # Automatically log in user
      # TODO: Is there a more elegant way to do this?
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Welcome to Twitter-land!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followerships_helper.rb
module FollowershipsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followerships/create.html.erb
<h1>Followerships#create</h1>
<p>Find me in app/views/followerships/create.html.erb</p>

app/views/followerships/destroy.html.erb
<h1>Followerships#destroy</h1>
<p>Find me in app/views/followerships/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="header">
    <div class="container">
      <a id='logo' href='/'><h1>Twitter!</h1></a>
      <ul id="main-nav">
        <% if is_user_authenticated? %>
          <li><%= current_user.email %></li>
          <li>|</li>
          <li><a href="#">Settings</a></li>
          <li><a href="#">Help</a></li>
          <li><%= link_to "Logout", logout_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="container">

    <% if notice %>
      <div class="alert"><%= notice %></div>
    <% elsif alert %>
      <div class="alert"><%= alert %></div>
    <% end %>

    <%= yield %>

    <div id="footer">
      <ul id="footer-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Jobs</a></li>
        <li><a href="#">Terms of Use</a></li>
        <li><a href="#">Privacy Policy</a></li>
      </ul>
    </div>
  </div>

</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/help.html.erb
<h1>Main#help</h1>
<p>Find me in app/views/main/help.html.erb</p>

app/views/main/home.html.erb
<% if is_user_authenticated? %>

  <div class="row">
    <div class="span4" id="user_info">
      <div class="well">
        <%= render 'shared/user_info' %>
      </div>
      <div class="well">
        <%= render 'shared/posts_create' %>
      </div>
    </div>
    <div class="span8" id="user_feed">
      <div class="feed_header">My Feed</div>
      <%= render 'shared/user_feed' %>
    </div>
  </div>
<% else %>
  Please log in to see more!
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/shared/_posts_create.html.erb
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.text_area :content, :id => "tweet-box",  :placeholder => "What's on your mind?"  %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet!", :class => "btn btn-primary", :id => "btn-tweet" %>
  </div>
<% end %>

app/views/shared/_user_feed.html.erb
<ul id="user_feed_list">
  <% if @posts.nil? || @posts.count == 0 %>
    You have no posts :(<br />
    BUT, You can fix it on the left! :)
  <% end %>
  <% @posts.each do |post| %>
    <li class="post">
      <div>
        <b><%= post.user.name %></b> - <%= post.user.email %><br />
        <i><%= post.content %></i>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_user_info.html.erb
<h3><%= current_user.email %></h3>
<div><%= current_user.posts.count %> Posts!</div>
<div><%= current_user.following.count %> Following</div>
<div><%= current_user.followers.count %> Follower</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-error">
    <ul>
      <% for message in @user.errors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <div class="span4 offset4">
    <div class="well">
      <h2>Sign Up</h2>

      <%= form_for @user do |f| %>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="actions"><%= f.submit :class => "btn btn-primary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row" id="main_profile">
  <div class="span8">
    <div class="user_profile">
      <span class="user_profile_name"><%= @user.name %></span> - <span class="user_profile_email"><%= @user.email %></span>
    </div>
  </div>
  <div class="span4">
    <div class="well">
      <div><%= @user.posts.count %> Posts!</div>
      <div><%= @user.following.count %> Following</div>
      <div><%= @user.followers.count %> Follower</div>
      <br />
      <% if is_user_authenticated? %>
        <% if current_user.id != @user.id %>
          <% if current_user.following?(@user) %>
            <%= form_for current_user.followerships.find_by_followed_id(@user), :html => { :method => :delete } do |f| %>
              <%= f.submit "Un-Follow!", :class => "btn btn-primary" %>
            <% end %>
          <% else %>
            <%= form_for current_user.followerships.build(:followed_id => @user.id) do |f| %>
              <div><%= f.hidden_field :followed_id %></div>
              <%= f.submit "Follow!", :class => "btn btn-primary" %>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        Log in to follow!
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="feed_header">Tweets</div>
  <%= render 'shared/user_feed' %>
</div>